import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { FloatingDockDemo } from "@/components/Header";
import  FooterComponent  from "@/components/footer";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "AIScend",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`bg-black text-white ${geistSans.variable} ${geistMono.variable} antialiased`}>
        <FloatingDockDemo />
        {children}
        <FooterComponent />
      </body>
    </html>
  );
}
